module.exports = {
  NO_PROFILE: 'NO_PROFILE',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_CLOSED: 'ROOM_CLOSED',
  NOT_MEMBER: 'NOT_MEMBER',
  NOT_OWNER: 'NOT_OWNER',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_TARGET: 'INVALID_TARGET',
  CODE_GENERATION_FAILED: 'CODE_GENERATION_FAILED'
}
